### ISSUE TITLE
Encountering KeyError and NaN label issues with end-to-end experiments

### ISSUE THREAD

**Issue by FUTUREEEEEE** [LechengKong/OneForAll#1] opened 2023-11-05 09:31 UTC
Hi lecheng, 

Thanks for the open source code, I run into an error when I use `end-to-end experiments`.

First is the KeyError: 'prompt_node_edge_feat' on dataset coralink and coranode.
![image](https://github.com/LechengKong/OneForAll/assets/52389798/ea7c2009-3d10-4a28-a839-57841dd7020c)

Second is the nan in labels on chempcba chemhiv chemblpre datasets. 
![image](https://github.com/LechengKong/OneForAll/assets/52389798/1e88a1be-f99a-4d9b-935e-d2c785846f1e)
![image](https://github.com/LechengKong/OneForAll/assets/52389798/2f84ad6f-9307-4d2e-b549-08adedf60774)

Could you please help me understand what might be causing these issues and how to resolve them?

**Comment by LechengKong** [comment] 2023-11-05 23:00
Hi @FUTUREEEEEE ,

Thank you for being so interested in our work! Sorry about the naming issues. They should be fixed in the most recent commit. A version mismatch in pull request caused it. You can follow the new Readme to run the code. We are still cleaning up the low resource version and combining it into the e2e version, it should be online soon.

For the nan label issue, you should see nan labels in chempcba and chemblepre datasets, as some tasks indeed have no ground truth. The recent commit will ignore these unmeasured labels as well, so the code should run correctly. During inference, we also ignore these labels.

Hope this solves the issues. If they persist, feel free to leave a comment.

Best,
@LechengKong

**Comment by FUTUREEEEEE** [comment] 2023-11-08 00:34
> Hi @FUTUREEEEEE ,
> 
> Thank you for being so interested in our work! Sorry about the naming issues. They should be fixed in the most recent commit. A version mismatch in pull request caused it. You can follow the new Readme to run the code. We are still cleaning up the low resource version and combining it into the e2e version, it should be online soon.
> 
> For the nan label issue, you should see nan labels in chempcba and chemblepre datasets, as some tasks indeed have no ground truth. The recent commit will ignore these unmeasured labels as well, so the code should run correctly. During inference, we also ignore these labels.
> 
> Hope this solves the issues. If they persist, feel free to leave a comment.
> 
> Best, @LechengKong

Hi LeCheng,

I appreciate your swift response and the confirmation that the previously reported bugs will be addressed., however, I encountered another one when I train the model.
![image](https://github.com/LechengKong/OneForAll/assets/52389798/a719610d-2d0d-4aeb-94fa-99df41094655)

**Comment by LechengKong** [comment] 2023-11-08 04:47
Hi @FUTUREEEEEE ,

Looks like it is a runtime error, do you mind sharing the command you used so we can reproduce the error? Thanks

@LechengKong

**Comment by FUTUREEEEEE** [comment] 2023-11-08 13:54
I use `python run_cdm.py --override e2e_all_config.yaml`.

**Comment by LechengKong** [comment] 2023-11-09 04:32
It should be fixed by the most recent commit. No need to regenerate datasets.

Again thank you for helping us correct the repo. This project is still under rapid development and there are mismatching issues between our local version and online version, sorry about the inconvenience.

**Closed as completed** 2023-12-01 03:13 UTC
